### ISSUE TITLE
Add `Set selected tracks record input to audio mono {5..16}.lua`

### ISSUE THREAD

**Issue by tkna91** [X-Raym/REAPER-ReaScripts#26]
4 mono inputs can be set by the script below.
https://github.com/X-Raym/REAPER-ReaScripts/blob/129f587709e3e49333a788f1ac8c72ab5acbec5e/Track%20Properties/X-Raym_Set%20selected%20tracks%20record%20input%20to%20X.lua#L15

I have an audio interface with 8 track inputs.
I feel that if I can get up to 16 inputs, it will be fine in most cases.
- Is it possible to add another 5-16 Inputs?
- This is a request for another script, is it possible to add Stereo Input up to a combination of '1&2' to '15&16'?

**Comment by X-Raym** [comment]
@tkna91 Hi,

I just have updated the script with the following:

```
 * v1.0.1 (2024-05-21)
  # Stereo pairs 1-2, 3-4, 5-6, 7-8
  # All channels for the MIDI version
  # 8 Mono versions
```

I think adding 16 entries for this scripts is a bit overkill for most users (first time I got the request since the script release), and I don't want to spam users action list with too much variations of the same action. Though, you can preset scripts (https://github.com/X-Raym/REAPER-ReaScripts/tree/master/Templates/Script%20Preset) and just name them "Script: X-Raym_Set selected tracks record input to audio mono 1.lua" and rename it to "9-10-11-12 etc", and import these new files into the action list manually, and it will works.

For stereo version, I haven't made pairs like 2-3, 4-5 etc but you can create them the same way. Not that pairs can only be consecutive in REAPER.

Trick; you can use the presets scripts to name your actions like "Set track input to GUITAR" for eg, and have the variable `force_script_name` set to a regular input number that will be processed instead of the file name directly.

If you these enhancements are useful to you, I invite you to make a [donation](https://www.paypal.com/paypalme/extremraym). Thanks for your consideration!
